binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: ${upper_devicename} Button
    on_press:
      - switch.toggle: relay
   
switch:
  - platform: restart
    name: ${upper_devicename} Restart
  
  - platform: gpio
    name: ${upper_devicename} Steckdose
    icon: "mdi:power-socket"
    pin: GPIO12
    id: relay
    on_turn_on:
      then:
        - output.turn_on: gpio4
    on_turn_off:
      then:
        - output.turn_off: gpio4

status_led:
  pin:
    number: GPIO5
    inverted: true
    
output:
  - platform: esp8266_pwm
    id: gpio4
    pin: GPIO4
    inverted: True