# Enable Home Assistant API
mqtt:
  broker: "homeassistant.lan"
  username: esphome
  password: !secret mqtt_password
  discovery: true
  topic_prefix: esphome/$devicename
  
web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

ota:
  - platform: esphome
    password: !secret ota_password
  
logger:
