# Enable Home Assistant API
api:
  password: !secret api_password
  
web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

ota:
  password: !secret ota_password
  
logger:
