# Enable Home Assistant API
mqtt:
  broker: "share.lan"
  discovery: true
  topic_prefix: esphome/$devicename
  
web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

ota:
  password: !secret ota_password
  
logger:
