substitutions:
  devicename: ble-proxy
  upper_devicename: BLE Proxy

esphome:
  name: $devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

esp32_ble_tracker:
  # scan_parameters:
  #   interval: 1100ms
  #   window: 1100ms
  #   active: true

bluetooth_proxy:
  active: true
  
api:

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    update_interval: 60s
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:C0:CA:92"
    temperature:
      name: "ATC Temperature"
    humidity:
      name: "ATC Humidity"
    battery_level:
      name: "ATC Battery-Level"
    battery_voltage:
      name: "ATC Battery-Voltage"
    signal_strength:
      name: "ATC Signal"
    
<<: !include base.yaml
<<: !include wifi.yaml
